[DEBUG] [20-11-22] [org.apache.ibatis.logging.LogFactory] Logging initialized using 'class org.apache.ibatis.logging.log4j.Log4jImpl' adapter.
[DEBUG] [20-11-22] [org.apache.ibatis.logging.LogFactory] Logging initialized using 'class org.apache.ibatis.logging.log4j.Log4jImpl' adapter.
[DEBUG] [20-11-22] [org.apache.ibatis.datasource.pooled.PooledDataSource] PooledDataSource forcefully closed/removed all connections.
[DEBUG] [20-11-22] [org.apache.ibatis.datasource.pooled.PooledDataSource] PooledDataSource forcefully closed/removed all connections.
[DEBUG] [20-11-22] [org.apache.ibatis.datasource.pooled.PooledDataSource] PooledDataSource forcefully closed/removed all connections.
[DEBUG] [20-11-22] [org.apache.ibatis.datasource.pooled.PooledDataSource] PooledDataSource forcefully closed/removed all connections.
[DEBUG] [20-11-22] [org.apache.ibatis.transaction.jdbc.JdbcTransaction] Opening JDBC Connection
[DEBUG] [20-11-22] [org.apache.ibatis.datasource.pooled.PooledDataSource] Created connection 796667727.
[DEBUG] [20-11-22] [org.apache.ibatis.transaction.jdbc.JdbcTransaction] Setting autocommit to false on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@2f7c2f4f]
[DEBUG] [20-11-22] [com.halo.mapper.UserMapper.getUserByID] ==>  Preparing: select * from mybatis.user where id = ?;
[DEBUG] [20-11-22] [com.halo.mapper.UserMapper.getUserByID] ==> Parameters: 2(Integer)
[DEBUG] [20-11-22] [com.halo.mapper.UserMapper.getUserByID] <==      Total: 1
[DEBUG] [20-11-22] [org.apache.ibatis.transaction.jdbc.JdbcTransaction] Resetting autocommit to true on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@2f7c2f4f]
[DEBUG] [20-11-22] [org.apache.ibatis.transaction.jdbc.JdbcTransaction] Closing JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@2f7c2f4f]
[DEBUG] [20-11-22] [org.apache.ibatis.datasource.pooled.PooledDataSource] Returned connection 796667727 to pool.
[INFO] [20-11-22] [mapper.UserMapperTest] info:进入了testLog4j
[DEBUG] [20-11-22] [mapper.UserMapperTest] debug:进入了testLog4j
[ERROR] [20-11-22] [mapper.UserMapperTest] error:进入了testLog4j
[DEBUG] [21-05-24] [org.apache.ibatis.logging.LogFactory] Logging initialized using 'class org.apache.ibatis.logging.log4j.Log4jImpl' adapter.
[DEBUG] [21-05-24] [org.apache.ibatis.logging.LogFactory] Logging initialized using 'class org.apache.ibatis.logging.log4j.Log4jImpl' adapter.
[DEBUG] [21-05-24] [org.apache.ibatis.datasource.pooled.PooledDataSource] PooledDataSource forcefully closed/removed all connections.
[DEBUG] [21-05-24] [org.apache.ibatis.datasource.pooled.PooledDataSource] PooledDataSource forcefully closed/removed all connections.
[DEBUG] [21-05-24] [org.apache.ibatis.datasource.pooled.PooledDataSource] PooledDataSource forcefully closed/removed all connections.
[DEBUG] [21-05-24] [org.apache.ibatis.datasource.pooled.PooledDataSource] PooledDataSource forcefully closed/removed all connections.
[DEBUG] [21-05-24] [org.apache.ibatis.transaction.jdbc.JdbcTransaction] Opening JDBC Connection
[DEBUG] [21-05-24] [org.apache.ibatis.datasource.pooled.PooledDataSource] Created connection 1902430796.
[DEBUG] [21-05-24] [org.apache.ibatis.transaction.jdbc.JdbcTransaction] Setting autocommit to false on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@7164ca4c]
[DEBUG] [21-05-24] [com.halo.mapper.UserMapper.getUserByID] ==>  Preparing: select * from mybatis.user where id = ?;
[DEBUG] [21-05-24] [com.halo.mapper.UserMapper.getUserByID] ==> Parameters: 2(Integer)
[DEBUG] [21-05-24] [com.halo.mapper.UserMapper.getUserByID] <==      Total: 1
[DEBUG] [21-05-24] [org.apache.ibatis.transaction.jdbc.JdbcTransaction] Resetting autocommit to true on JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@7164ca4c]
[DEBUG] [21-05-24] [org.apache.ibatis.transaction.jdbc.JdbcTransaction] Closing JDBC Connection [com.mysql.cj.jdbc.ConnectionImpl@7164ca4c]
[DEBUG] [21-05-24] [org.apache.ibatis.datasource.pooled.PooledDataSource] Returned connection 1902430796 to pool.
[INFO] [21-05-24] [mapper.UserMapperTest] info:进入了testLog4j
[DEBUG] [21-05-24] [mapper.UserMapperTest] debug:进入了testLog4j
[ERROR] [21-05-24] [mapper.UserMapperTest] error:进入了testLog4j
